# =============================================================================
# BASIC PRESET CONFIGURATION
# Features: Sign-in, Call Test (basic), Call History (basic), Feedback
# =============================================================================
basic:
  preset: "basic"
  
  pages:
    signin: true
    dashboard: false
    call_test: true
    call_history: true
    chat_history: false
    feedback: true

  components:
    header:
      dashboard_menu: false
      call_test_menu: true
      chat_test_menu: false
      call_history_menu: true
      feedback_menu: true
      user_avatar_dropdown: true

    call_test:
      tryout_component: true
      talk_to_vaani_component: true
      
      talk_to_vaani:
        name_field: true
        country_code_selector: true
        phone_number_field: true
        voice_selection: false  # No male/female avatars
        voice_options_dropdown: false  # No voice variants
        use_case_dropdown: true
        trigger_call_button: true

    call_history:
      view_mode_toggle: false  # No toggle needed
      filters_section: false
      search_functionality: false
      date_range_filter: false
      status_filter: false
      direction_filter: false
      selection_checkboxes: false  # No selection
      bulk_operations: false
      csv_download: false  # No download
      
      call_details_sidebar:
        audio_recording: false  # No audio
        transcript_section: true
        summary_section: true
        conversation_evaluation: false  # No evaluation
        entity_extraction: false  # No extraction

    chat_history:
      filters_section: false
      search_functionality: false
      date_range_filter: false
      selection_checkboxes: false
      csv_download: false
      
      chat_details_sidebar:
        chat_info_section: false
        transcript_section: false
        summary_section: false

    dashboard:
      call_metrics: false
      chat_metrics: false
      period_toggle: false
      metrics_cards: false
      call_trends_chart: false
      chat_trends_chart: false
      duration_chart: false

    feedback:
      rating_sliders: true
      feedback_text_area: true
      submit_button: true

    global:
      floating_chat_widget: false  # No chat
      footer: true

  api:
    call_endpoints: true
    chat_endpoints: false
    dashboard_endpoints: false
    feedback_endpoints: true

  build:
    tree_shake_disabled_features: true
    remove_unused_routes: true
    conditional_imports: true

---

# =============================================================================
# CALL-ONLY PRESET CONFIGURATION  
# Features: Basic + Voice options, Dashboard (call metrics only)
# =============================================================================
call-only:
  preset: "call-only"
  
  pages:
    signin: true
    dashboard: true
    call_test: true
    call_history: true
    chat_history: false
    feedback: true

  components:
    header:
      dashboard_menu: true
      call_test_menu: true
      chat_test_menu: false
      call_history_menu: true
      feedback_menu: true
      user_avatar_dropdown: true

    call_test:
      tryout_component: true
      talk_to_vaani_component: true
      
      talk_to_vaani:
        name_field: true
        country_code_selector: true
        phone_number_field: true
        voice_selection: true  # Include voice selection
        voice_options_dropdown: true  # Include voice variants
        use_case_dropdown: true
        trigger_call_button: true

    call_history:
      view_mode_toggle: false  # Only calls, no toggle needed
      filters_section: true
      search_functionality: true
      date_range_filter: true
      status_filter: true
      direction_filter: true
      selection_checkboxes: true
      bulk_operations: true
      csv_download: true
      
      call_details_sidebar:
        audio_recording: true
        transcript_section: true
        summary_section: true
        conversation_evaluation: true
        entity_extraction: true

    chat_history:
      filters_section: false
      search_functionality: false
      date_range_filter: false
      selection_checkboxes: false
      csv_download: false
      
      chat_details_sidebar:
        chat_info_section: false
        transcript_section: false
        summary_section: false

    dashboard:
      call_metrics: true  # Only call metrics
      chat_metrics: false
      period_toggle: true
      metrics_cards: true
      call_trends_chart: true
      chat_trends_chart: false
      duration_chart: true

    feedback:
      rating_sliders: true
      feedback_text_area: true
      submit_button: true

    global:
      floating_chat_widget: false  # No chat widget
      footer: true

  api:
    call_endpoints: true
    chat_endpoints: false
    dashboard_endpoints: true
    feedback_endpoints: true

  build:
    tree_shake_disabled_features: true
    remove_unused_routes: true
    conditional_imports: true

---

# =============================================================================
# CHAT-ONLY PRESET CONFIGURATION
# Features: Everything except Call Test page, Dashboard with chat metrics
# =============================================================================
chat-only:
  preset: "chat-only"
  
  pages:
    signin: true
    dashboard: true
    call_test: false  # No call test page
    call_history: false
    chat_history: true
    feedback: true

  components:
    header:
      dashboard_menu: true
      call_test_menu: false  # No call test menu
      chat_test_menu: false  # No separate chat test menu
      call_history_menu: false
      feedback_menu: true
      user_avatar_dropdown: true

    call_test:
      tryout_component: false
      talk_to_vaani_component: false
      
      talk_to_vaani:
        name_field: false
        country_code_selector: false
        phone_number_field: false
        voice_selection: false
        voice_options_dropdown: false
        use_case_dropdown: false
        trigger_call_button: false

    call_history:
      view_mode_toggle: false
      filters_section: false
      search_functionality: false
      date_range_filter: false
      status_filter: false
      direction_filter: false
      selection_checkboxes: false
      bulk_operations: false
      csv_download: false
      
      call_details_sidebar:
        audio_recording: false
        transcript_section: false
        summary_section: false
        conversation_evaluation: false
        entity_extraction: false

    chat_history:
      filters_section: true
      search_functionality: true
      date_range_filter: true
      selection_checkboxes: true
      csv_download: true
      
      chat_details_sidebar:
        chat_info_section: true
        transcript_section: true
        summary_section: true

    dashboard:
      call_metrics: false
      chat_metrics: true  # Only chat metrics
      period_toggle: true
      metrics_cards: true
      call_trends_chart: false
      chat_trends_chart: true
      duration_chart: false  # No duration for chats

    feedback:
      rating_sliders: true
      feedback_text_area: true
      submit_button: true

    global:
      floating_chat_widget: true  # Chat widget needed
      footer: true

  api:
    call_endpoints: false
    chat_endpoints: true
    dashboard_endpoints: true
    feedback_endpoints: true

  build:
    tree_shake_disabled_features: true
    remove_unused_routes: true
    conditional_imports: true

---

# =============================================================================
# FULL PRESET CONFIGURATION
# Features: Everything enabled
# =============================================================================
full:
  preset: "full"
  
  pages:
    signin: true
    dashboard: true
    call_test: true
    call_history: true
    chat_history: true
    feedback: true

  components:
    header:
      dashboard_menu: true
      call_test_menu: true
      chat_test_menu: true
      call_history_menu: true
      feedback_menu: true
      user_avatar_dropdown: true

    call_test:
      tryout_component: true
      talk_to_vaani_component: true
      
      talk_to_vaani:
        name_field: true
        country_code_selector: true
        phone_number_field: true
        voice_selection: true
        voice_options_dropdown: true
        use_case_dropdown: true
        trigger_call_button: true

    call_history:
      view_mode_toggle: true  # calls/chats/all toggle
      filters_section: true
      search_functionality: true
      date_range_filter: true
      status_filter: true
      direction_filter: true
      selection_checkboxes: true
      bulk_operations: true
      csv_download: true
      
      call_details_sidebar:
        audio_recording: true
        transcript_section: true
        summary_section: true
        conversation_evaluation: true
        entity_extraction: true

    chat_history:
      filters_section: true
      search_functionality: true
      date_range_filter: true
      selection_checkboxes: true
      csv_download: true
      
      chat_details_sidebar:
        chat_info_section: true
        transcript_section: true
        summary_section: true

    dashboard:
      call_metrics: true
      chat_metrics: true
      period_toggle: true
      metrics_cards: true
      call_trends_chart: true
      chat_trends_chart: true
      duration_chart: true

    feedback:
      rating_sliders: true
      feedback_text_area: true
      submit_button: true

    global:
      floating_chat_widget: true
      footer: true

  api:
    call_endpoints: true
    chat_endpoints: true
    dashboard_endpoints: true
    feedback_endpoints: true

  build:
    tree_shake_disabled_features: true
    remove_unused_routes: true
    conditional_imports: true