client_name: codeyoung
mode: SIP # SIP, CONSOLE
record_audio: False

store_transcription:
  switch: True # True, False
  where: s3 # local, s3, both

welcome_msg: True
use_rag: True
rag_file: "blank"
bg_audio: False
idle_call_hungup: True
llm: openai
model: gpt4o
show_tool_call_in_chat: True
TTS: cartesia # elevenlabs/cartesia/aws/neuphonic - azure/playai is not working currently.


chat_session_timeouts:
  # Time in seconds after which an inactive chat session is considered dormant
  inactivity_timeout: 10  # 30 minutes
  
  # Time in seconds after which a dormant session will be automatically ended
  dormant_session_cleanup: 20  # 60 minutes
  
  # How often to check for dormant sessions (in seconds)
  cleanup_interval: 5  # 5 minutes
  
  # Maximum duration for a single chat session (in seconds)
  max_session_duration: 300  # 2 hours
  
  # Warning message time before session timeout (in seconds)
  warning_before_timeout: 8  # 5 minutes before timeout

# Session management
session_management:
  # Enable automatic cleanup of dormant sessions
  enable_auto_cleanup: True
  
  # Enable session warnings before timeout
  enable_timeout_warnings: True
  
  # Maximum concurrent chat sessions per user
  max_concurrent_sessions: 3


telephony: twilio